# Generated by Django 2.1.2 on 2018-11-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='url别名'),
        ),
    ]
