# Generated by Django 2.1.2 on 2018-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_classstudyrecord_student_studentstudyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64, verbose_name='权限'),
        ),
    ]
