# Generated by Django 2.1.2 on 2018-11-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20181119_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstudyrecord',
            unique_together={('student', 'classstudyrecord')},
        ),
    ]
