# Generated by Django 2.1.4 on 2019-03-29 11:11

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('jd_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(default='', help_text='用户注册平台的昵称', max_length=128, verbose_name='用户名称')),
                ('phone', models.CharField(default='', help_text='手机号', max_length=11, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, default='', help_text='昵称', max_length=50, verbose_name='昵称')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '平台自主用户表',
                'verbose_name_plural': '平台自主用户表',
                'db_table': 'jd_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JdAuthUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', help_text='用户唯一ID', max_length=128, verbose_name='用户唯一ID')),
                ('user_name', models.CharField(default='', help_text='授权使用应用时的用户名称，包括子账户名称', max_length=128, verbose_name='授权用户名称')),
                ('item_code', models.CharField(default='', help_text='应用服务编码', max_length=32, verbose_name='应用服务编码')),
                ('article_num', models.IntegerField(default=0, help_text='不确定作用', verbose_name='未知')),
                ('version_no', models.IntegerField(default=0, help_text='版本号', verbose_name='版本号')),
                ('app_end_date', models.IntegerField(default=0, help_text='服务到期时间', verbose_name='服务到期时间')),
                ('access_token', models.CharField(default='', help_text='令牌Token', max_length=128, verbose_name='令牌Token')),
                ('refresh_token', models.CharField(default='', help_text='令牌刷新凭证', max_length=128, verbose_name='令牌刷新凭证')),
                ('expires_in', models.IntegerField(default=0, help_text='令牌Token失效时间', verbose_name='令牌Token失效时间')),
                ('auth_start_time', models.IntegerField(default=0, help_text='服务登录授权时间点', verbose_name='服务登录授权时间点')),
                ('auth_end_time', models.IntegerField(default=0, help_text='服务登录授权到期时间点', verbose_name='服务登录授权到期时间点')),
                ('is_first_sync', models.BooleanField(default=True, help_text='是否是第一次同步数据', verbose_name='是否是第一次同步数据')),
                ('shop', models.ForeignKey(db_column='shop_id', help_text='店铺ID', on_delete=django.db.models.deletion.CASCADE, to='jd_shop.JdShopInfoModel', verbose_name='店铺ID')),
                ('user', models.ForeignKey(db_column='user_id', help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '京东授权用户表',
                'verbose_name_plural': '京东授权用户表',
                'db_table': 'jd_auth_user',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', help_text='验证码', max_length=10, verbose_name='验证码')),
                ('phone', models.CharField(default='', help_text='电话', max_length=11, verbose_name='电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '短信验证',
                'verbose_name_plural': '短信验证',
                'db_table': 'jd_verify_code',
                'managed': True,
            },
        ),
    ]
