# Generated by Django 2.1.2 on 2018-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_customer_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(default=12, to='app01.Permission'),
        ),
    ]
