# Generated by Django 2.1.4 on 2019-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankMonitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(default='', help_text='京东商品的SPU_ID', verbose_name='商品ID')),
                ('goods_name', models.CharField(default='', help_text='商品名称', max_length=255, verbose_name='商品名称')),
                ('web_rank', models.CharField(default='', help_text='Web端排名信息', max_length=64, verbose_name='Web端排名信息')),
                ('web_rank_diff', models.IntegerField(default=0, help_text='Web端排名差值', verbose_name='Web端排名差值')),
                ('wap_rank', models.CharField(default='', help_text='Wap端排名信息', max_length=64, verbose_name='Wap端排名信息')),
                ('wap_rank_diff', models.IntegerField(default=0, help_text='Wap端排名差值', verbose_name='Wap端排名差值')),
                ('wx_rank', models.CharField(default='', help_text='Wx端排名信息', max_length=64, verbose_name='Wx端排名信息')),
                ('wx_rank_diff', models.IntegerField(default=0, help_text='Wx端排名差值', verbose_name='Wx端排名差值')),
                ('qq_rank', models.CharField(default='', help_text='QQ端排名信息', max_length=64, verbose_name='QQ端排名信息')),
                ('qq_rank_diff', models.IntegerField(default=0, help_text='QQ端排名差值', verbose_name='QQ端排名差值')),
                ('keyword', models.CharField(default='', help_text='关键词', max_length=255, verbose_name='关键词')),
                ('cate_id', models.CharField(default='', help_text='类目ID组合', max_length=16, verbose_name='类目ID组合')),
                ('cate_name', models.CharField(default='', help_text='类目名称', max_length=255, verbose_name='类目名称')),
                ('sku_id', models.IntegerField(default=0, help_text='京东商品SKU_ID，SPU_ID对应下的多个SKU_ID', verbose_name='商品SKU_ID')),
                ('sku_name', models.CharField(default='', help_text='SKU名称', max_length=255, verbose_name='SKU名称')),
                ('is_monitor', models.BooleanField(default=False, help_text='是否已监控', verbose_name='是否已监控')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '排名监控',
                'verbose_name_plural': '排名监控',
                'db_table': 'rank_monitor',
                'ordering': ['-updated_time'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rankmonitormodel',
            unique_together={('goods_id', 'updated_time')},
        ),
    ]
